# Generated by Django 4.2.2 on 2023-07-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_remove_houses_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='sqr_feet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
