# Generated by Django 4.2.2 on 2023-07-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_houses_sqr_feet'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='house_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
