# Generated by Django 4.2.2 on 2023-07-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_houses_house_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=50)),
                ('land_category', models.CharField(choices=[('Residential', 'Residential'), ('Agricultural', 'Agricultural')], max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
