# Generated by Django 4.2.2 on 2023-07-09 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 7, 9, 10, 27, 51, 924461, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
