# Generated by Django 4.2.2 on 2023-07-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_land_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='land_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='land',
            name='land_category',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Agricultural', 'Agricultural'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Raw Land', 'Raw Land')], max_length=50),
        ),
    ]
