# Generated by Django 4.2.2 on 2023-07-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0007_land_land_size_alter_land_land_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='agent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='houses.agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='land',
            name='agent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='houses.agent'),
            preserve_default=False,
        ),
    ]
